"""Add is_quick_tweet field to Tweet model

Revision ID: 669cff5b7bf8
Revises: 
Create Date: 2025-04-27 01:13:02.297529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669cff5b7bf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quick_tweet', sa.Boolean(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=280),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sentiment_label',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.alter_column('sentiment_label',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=280),
               nullable=True)
        batch_op.drop_column('is_quick_tweet')

    # ### end Alembic commands ###
